# Generated by Django 5.0.2 on 2024-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
