# Generated by Django 5.0.2 on 2024-04-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0002_vacancy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Experiencia laboral en meses'),
        ),
    ]
