# Generated by Django 5.0.2 on 2024-04-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0003_employee_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.IntegerField(default=0, verbose_name='Experiencia laboral en meses'),
        ),
    ]
