# Generated by Django 5.0.2 on 2024-04-25 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0004_alter_employee_work_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applyVacancy',
        ),
    ]
