# Generated by Django 5.0.2 on 2024-04-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0005_delete_applyvacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_to', to='TalentSwapApp.employee')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='TalentSwapApp.vacancy')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
