# Generated by Django 5.0.2 on 2024-04-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0006_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
