# Generated by Django 5.0.2 on 2024-04-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0007_application_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/'),
        ),
    ]
