# Generated by Django 5.0.2 on 2024-04-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0008_alter_vacancy_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
