# Generated by Django 5.0.2 on 2024-05-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0013_employeerating_vacancyrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
