# Generated by Django 4.2.7 on 2024-10-05 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TalentSwapApp', '0014_alter_company_options_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='TalentSwapApp.company'),
        ),
    ]
